# Site settings
author: Audra Tallman
title: Audi's Adventures
header-img: img/home-bg.png
email: audra.tallman@hotmail.com
copyright_name: Audra Tallman
description: > # this means to ignore newlines until "baseurl:"
  A beginner's journey in coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: mrsatallman
github_username:  audra-tallman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
